### ISSUE TITLE
Gradle 5 compatibility

### ISSUE THREAD

**Issue by msevcenko** [stoicflame/enunciate-gradle#25]
Is the lastest version 2.12.0 compatible with Gradle 5? When running with Gradle 5.5.1 (via Eclipse Buildship plugin, if it is relevant) I get:
```
org.gradle.tooling.BuildException: Could not fetch model of type 'GradleBuild' using Gradle installation 'c:\Program Files\gradle-5.5.1'.
...
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;
	at com.webcohesion.enunciate.gradle.EnunciateTask.<init>(EnunciateTask.java:75)
	at com.webcohesion.enunciate.gradle.EnunciateTask_Decorated.<init>(Unknown Source)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:153)
	at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:389)
	at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:67)
```

Seems to me that Enunciate plugin uses older Gradle API that is no longer supported in Gradle 5.

**Comment by jskov-jyskebank-dk** [comment]
I use it with Gradle 5.6.1, so that is not the problem.

With that said, you are now the second to see this problem (see #24)

Could you create a small project on github that demonstrates the problem?

**Comment by msevcenko** [comment]
No need for a project, you just need to include the plugin and run.
build.gradle:
```plugins { id "com.webcohesion.enunciate" version "2.10.1" }```
running "gradle enunciate" runs the task in gradle 3.5.1 (complains about missing enunciate.xml).
running with gradle 5.5.1 fails with error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\var\git\experiments\enunciate\build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'com.webcohesion.enunciate', version: '2.10.1']
> Failed to apply plugin [id 'com.webcohesion.enunciate']
   > Could not create task ':enunciate'.
      > Could not create task of type 'EnunciateTask'.
         > org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;
```
I did not try Gradle 5.6.1, maybe the problem is fixed there.

**Comment by msevcenko** [comment]
Just tried 5.6.2, same error, no such method.
```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;
        at com.webcohesion.enunciate.gradle.EnunciateTask.<init>(EnunciateTask.java:75)
        at com.webcohesion.enunciate.gradle.EnunciateTask_Decorated.<init>(Unknown Source)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:179)
        at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:395)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:49)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:72)
        ... 168 more
```

**Comment by msevcenko** [comment]
FYI, found an interesting reference: https://discuss.gradle.org/t/taskinputs-files-nosuchmethoderror/30122/7

Maybe you need to recompile against Gradle 3.0.

**Comment by jskov-jyskebank-dk** [comment]
This plugin gets built by Gradle 4.4, so that should not be the cause (as the link suggests).

But I will update it to build with Gradle 5.6.2.

On the up side, I can reproduce your problem from your description, thanks.
I am unsure why all our projects (200+) actually work... But it may be due to this plugin getting activated/included from another plugin.

I will try to find out.

**Comment by msevcenko** [comment]
> This plugin gets built by Gradle 4.4

You mean it is _compiled against_ Gradle 4.4 API / libraries? Just _building_ it with particular Gradle version does not mean much I think.

**Comment by jskov-jyskebank-dk** [comment]
It means the world, as the building Gradle supplies the API:
```
dependencies {
	compile gradleApi()
}

```

**Comment by msevcenko** [comment]
Ok.

Sorry I just double-check and it seems that 2.12.0 actually _does_ work. Looks like the broken version is only 2.10.1.

Looks like I did some mistake when upgrading enunciate to 2.12.0 so I incorrectly concluded that it didn't help.

**Comment by jskov-jyskebank-dk** [comment]
Ah. I only tested with 2.10.1 earlier, and that did fail.

But 2.12.0 does work with 5.6.2.


I will close this issue now. If anyone else see this problem, please provide a reproducible example, and I will look at it.

**Comment by msevcenko** [comment]
👍 Thanks and sorry for false alarm.
